### ISSUE TITLE
I'm having issues with digest verification...  

### ISSUE THREAD

**Issue by JigmeDatse** [mb-0/plex-gentoo-ebuilds#1]
```
 * Missing digest for '/var/lib/layman/Plex/media-tv/plex-media-server/plex-media-server-1.4.2.ebuild'
 * Digest verification failed:
 * /var/lib/layman/Plex/media-tv/plex-media-server/plex-media-server-1.4.1.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 10023
 * Expected: 10087
```

I'm working on fixing that locally, but it would be great that people not have issues with this.

**Comment by JigmeDatse** [comment]
I'm not sure what I got working, but through using repoman most of the complaints are gone.  Thank you for providing this.

**Comment by mb-0** [comment]
Hey JigmeDatse,

Thanks for reporting.
I made some changes so this can act as a local repo, updated readme accordingly, however I didn't have a way to test these changes properly - will keep this issue around until you or I can confirm that this looks better.

Thanks,
mb
